### ISSUE TITLE
Model 702 - Add bitfield symbols to IntIslandCatRtg and IntIslandCat

### ISSUE THREAD

**Issue by shelcrow** [sunspec/models#119] opened 2020-08-31 20:17 UTC

**Comment by jsbosch** [comment] 2020-09-24 20:42
Duplicate of #111?

**Comment by jsbosch** [comment] 2020-09-24 21:01
My reading of 1547-2018 is that the category is an enum not bitfield:

> 8.2.8 DER categories for intentional islands
A DER that participates in an intentional Area EPS island shall be categorized in one of the following
ways:

That said, maybe it makes sense to have the rating as a bitfield ("inverter can do this") but the setting as an enum ("I choose this one category"). Maybe this needs further group discussion?

Suggested values,  based on 1547-2018:

- UNCATEGORIZED
- INT_ISL_CAPABLE
- BLACK_START_CAPABLE
- ISO_CAPABLE

**Closed** 2020-11-02 22:52 UTC
